### ISSUE TITLE
Why is this activity diagram correct?

### ISSUE THREAD

**Issue by Jefferson111** [nusCS2113-AY1920S1/forum#104]
First issue I have, from what I have read and understood, authentication of the user is **independent** of wallet registration by user and balance checking. However, the diagram indicates that the authentication of the user must be checked first before checking wallet registration. 

The second issue I have is the prompt for cash payment before the end? Shouldn't it be executed at the point where I marked my `x`? (Prompt for cash payment should only happen when there is an error condition)

![image](https://user-images.githubusercontent.com/42374076/69471417-aecdab00-0dd9-11ea-9649-6a1bd05821f7.png)

This is taken from 1819S2 Part 2

**Comment by Jefferson111** [comment]
Ok, nevermind, identifying wallet service is not checking wallet registration.

**Comment by okkhoy** [comment]
prompt cash payment happens when any of the errors occur. There is nothing wrong in adding a prompt pay by cash at each X locations.

**Comment by aquohn** [comment]
Yes, but the issue is that it prompts for cash payment even along the success path.

**Comment by okkhoy** [comment]
Oh wait! You are right. My mistake; after pay for purchase, has to go to the end; not the one given.

**Comment by aquohn** [comment]
Doesn't it need to pass through all the join nodes too?

**Comment by Jefferson111** [comment]
With regards to this, I was thinking about [this](https://stackoverflow.com/questions/32299336/activity-diagram-with-multiple-end-points), which may allow it to not pass through the join nodes. As for directly pointing to the same end point, I am not sure.
> Doesn't it need to pass through all the join nodes too?

**Comment by Jefferson111** [comment]
https://stackoverflow.com/questions/41870513/how-to-show-attribute-as-readonly-in-uml
🤔
