### ISSUE TITLE
How to define macro in Java?

### ISSUE THREAD

**Issue by CEGLincoln** [nusCS2113-AY1920S1/forum#12]
I used to do this for C++:

```
#define LOOP(n) for(int i=0; i<n; i++)

int main(){
  LOOP(5){
    cout << "count: " << i << endl;
  }
}
```

can something similar be done on Java?

**Comment by aquohn** [comment]
Essentially, Java doesn't have a preprocessor, so Java can't do macros.

https://stackoverflow.com/questions/6525059/can-i-have-macros-in-java-source-files
