### ISSUE TITLE
How to construct arbitrary object in method?

### ISSUE THREAD

**Issue by aquohn** [nusCS2113-AY1920S1/forum#13]
Being a firm believer in the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle, I tried to write a function to create and add Tasks of various types. Essentially it looks like this:

   ```
private static Boolean addTask(ArrayList<Task> taskList, Class taskClass, String inputStr, String keyword, String cmd) {
        String[] addArr = {"Got it, I've added this task:", "", ""};
        Class[] oneString = {String.class};
        Class[] twoStrings = {String.class, String.class};

        if (keyword != null) { // Task type consists of two parts separated by a keyword
            String[] splitArr = inputStr.split(keyword, 2);
            if (splitArr.length < 2) {
                return false;
            } else {
                Constructor taskConst = taskClass.getConstructor(twoStrings);
                taskList.add(taskClass.cast(taskConst.newInstance(splitArr[0].substring(cmd.length()), splitArr[1])));
            }
        } else {
            Constructor taskConst = taskClass.getConstructor(oneString);
            taskList.add(taskClass.cast(taskConst.newInstance(inputStr.substring(cmd.length()))));
        }
        addArr[1] = "  " + taskList.get(taskList.size() - 1).toString();
        addArr[2] = "Now you have " + Integer.toString(taskList.size()) + " tasks in the list.";
        say(addArr);
        return true;
    }
```

Using the Constructor class in the Reflection package, I extract the relevant constructors and use them to create new instances of the required tasks. However, the typical recipe appears to require a line that looks something like:

```
Event newEvent = (Event) taskConst.newInstance(splitArr[0].substring(cmd.length()), splitArr[1]);
```
My question is, how do we do this generically?
```
taskClass newTask = (taskClass) taskConst.newInstance(splitArr[0].substring(cmd.length()), splitArr[1]);
```
fails (symbol not found), and the code above also fails (Object cannot be converted to Task). The Java documentation on Class and Constructor doesn't tell me how to extract the type from them in order to construct the object, and searching StackOverflow has resulted in pic related:

![StackOverflow](https://user-images.githubusercontent.com/42529939/63645581-546a7300-c734-11e9-8705-95a69f880bed.jpg)

This is quite confusing as this seems to be quite a simple application of OOP principles to me (a function that can operate on several different types of objects). Does my design violate some obscure tenet of Java philosophy?

**Comment by D-uke** [comment]
I'm not sure, but I got a feeling use Generics?
https://docs.oracle.com/javase/tutorial/extra/generics/methods.html

**Comment by j-lum** [comment]
Your problem probably stems from you not limiting your scope of your problem properly. In this case, you don't really want to construct "arbitrary" objects. If you rephrase your question and ask Google again, chances are that you will find more information about the factory pattern which seems to be one solution to your problem. (Note that its not even necessarily the most efficient solution.)

> This is quite confusing as this seems to be quite a simple application of OOP principles to me (a function that can operate on several different types of objects).

You might not have heard of the `extends` keyword but you should totally check it out! 

>  Does my design violate some obscure tenet of Java philosophy?

Yes and it's not even really obscure.  In general, `reflection` comes with a lot of caveats (blowing up runtime is a major one) that you will learn about later. If you read ahead in your textbook you can find yourself violating all of the SOLID principles in one small snippet of code!

**Comment by aquohn** [comment]
Thanks for the responses! I was able to get the issue working; I guess I was trying to use generics, just without knowing of their existence.

Thanks for the detailed writeup @j-lum! Although the factory pattern seems overkill, it's good to know about!

For those interested, the relevant syntax would be something like:

```
private static <T extends Task> void taskConstructor(Class<T> taskClass, String arg) {
    Class[] oneString = {String.class};
    Constructor ctor = taskClass.getConstructor(oneString);
    T newTask = (T) ctor(arg);
    // do stuff with new task
}
```
