### ISSUE TITLE
Program to an interface, not the implementation

### ISSUE THREAD

**Issue by Lucria** [nusCS2113-AY1920S1/forum#14]
Quick question, any penalisation if we do the above, instead of extension? I.e. using `implement` instead of `extend`

**Comment by okkhoy** [comment]
As such, it may be Ok to use `implements` instead of `extends`. However, if the exercise asks you to `extend` you should `extend`.

**Comment by Lucria** [comment]
So... Will there be any penalisation? Apologies if I'm violating the grading principles. will edit if needed E.g. level 4

**Comment by shamussy** [comment]
Yea, can we use abstract class before you mention that we have to use abstract classes? It feels weird knowing we can use them but we are not able to.

**Comment by okkhoy** [comment]
I definitely won't stop you guys from doing better if you want to (=> no penalty), but it would be better to do what is asked in the interest of discussions in the tutorial.
However, the condition on completing the tasks as per schedule remains.
