### ISSUE TITLE
Request for extension of deadline for Week 3 deliverables

### ISSUE THREAD

**Issue by Lucria** [nusCS2113-AY1920S1/forum#16]
As many have already raised on Slack (but there hasn't been any answer), can we ask for an extension for the Levels related to Week 3 (meaning Level 4, 5, 7, 8)? Due to these Levels being released on 23rd Feb, there are many people who only have 4 days left to accomplish these levels and have already raised requests for extension.

**Comment by okkhoy** [comment]
Sorry, the deadlines are firm.
