### ISSUE TITLE
Unable to push Level-8: Date and Time to remote

### ISSUE THREAD

**Issue by qjie7** [nusCS2113-AY1920S1/forum#18]
![Screenshot 2019-08-28 at 10 24 02 AM](https://user-images.githubusercontent.com/47095237/63821020-0052cf00-c97e-11e9-8d37-04b3578abd2b.png)

How can i solved this issue ? it seems that my origin/master is attached to the wrong commit. How can i change my origin/master back to my latest commit ?

**Comment by D-uke** [comment]
I think I got some bad news and good news for you. Good news is that you do not need to resolve this issue. Bad news is that I think we are supposed to work on the fork rather than a completely new repository. Meaning that all the while, you have been working on the wrong repository.

**Comment by D-uke** [comment]
On Intellij > Create new project from version control

Paste this [link](https://github.com/qjie7/duke) (for your case) when they ask for the source or the field that request for a link or something. (Can't remember if u need to login to Github on Intellij for this)

Then add that project to your source tree.

**Comment by qjie7** [comment]
Omg>.< is there a way for me to save from this mistake :( thanks for help.

**Comment by j-lum** [comment]
Pull the changes from your new repo into in a temporary branch on your fork and cherry pick/interactive rebase as required. If you're new to both interactive rebase and cherry picking, you can always start over if you don't want to learn those techniques.

**Comment by qjie7** [comment]
Thanks for the help. In the end I redo everything all over again >.<
