### ISSUE TITLE
Unable to join Slack channel

### ISSUE THREAD

**Issue by qjie7** [nusCS2113-AY1920S1/forum#19]
i am not able to join the slack channel. It says that my u.nus.edu email account is not register with the 2113 channel. P.S. I am able to see 2103 19/20 channel :0

**Comment by omupenguin** [comment]
Same here! I checked the workspaces that's linked to my NUS email, but the CS2113T workspace isn't there!

**Comment by okkhoy** [comment]
errr.. shouldn't be the case. please retry? Use this link if necessary: https://join.slack.com/t/nus-cs2113-ay1920s1/signup

**Comment by omupenguin** [comment]
Okay signed up and joined the channel. Thank you!
