### ISSUE TITLE
Gradle Tutorial Help 

### ISSUE THREAD

**Issue by D-uke** [nusCS2113-AY1920S1/forum#2]
I have fork the repo from here: https://github.com/nusCS2113-AY1920S1/duke

I tried followed through this tutorial: https://github.com/nusCS2113-AY1920S1/duke/blob/master/tutorials/gradleTutorial.md

But I couldn't make it past the very first step. Please help. Thank You.

**Comment by otonashixav** [comment]
I have to say that something doesn't add up here.

Anyway, the problem with the particular repo is that the branch "gradle" doesn't exist. If anyone would like to try out gradle, use the repo here if this issue hasn't been resolved by this time. 

Edit: upstream repo link removed - Akshay

**Comment by okkhoy** [comment]
@D-uke @otonashixav Things are in order now.

@otonashixav 
We don't want you guys to fork the upstream repository as it makes things messy for some of you to submit pull requests for assessment and feedback. In light of this, I am removing the link to the upstream se-edu repo from your comment

**Comment by D-uke** [comment]
❤❤❤❤❤
