### ISSUE TITLE
Question about Level-5

### ISSUE THREAD

**Issue by omupenguin** [nusCS2113-AY1920S1/forum#20]
Hello. Regarding Level-5, it seems that we mainly need to implement error handling for when a task is given without a description, and when an invalid command is given. If that is so, do I just tag my current version as done with Level-5? I understand that we are supposed to work on duke in increments, but I thought it kind of made sense that the features we add should have minimal errors, so I've already took those cases into account. What should I do and would I be penalized for completing two levels at once?

**Comment by okkhoy** [comment]
As much as I want you to do the increments in order, we (generally) won't penalize you for doing the right thing!
In this scenario, apply tag to the commit where you did error handling.

**Comment by omupenguin** [comment]
Will it be okay if it's on the same commit as another increment ID tag, or before the Level-4 tag?

**Comment by okkhoy** [comment]
>  apply tag to the commit where you did error handling

Decide where this is and please do the needful.
