### ISSUE TITLE
Question on tags

### ISSUE THREAD

**Issue by omupenguin** [nusCS2113-AY1920S1/forum#21]
Hello. I was checking through my previous commits, and I found out that my commits have (multiple?) tags on them. For instance:
![image](https://user-images.githubusercontent.com/42564029/63875788-ce318380-c9f6-11e9-855d-44931729f7e6.png)
This was supposed to be my level-2 tag, but it seems that there are more tags. Why is the Level-4 tag outlined? Is that to signify that is the current version? And what is up with all the other tags? 
However, on my 'releases' page, the relevant tags seem to be pointing to the correct commits where they were originally tagged. Would the extra tags on the other commit affect the how grading would work?

**Comment by okkhoy** [comment]
This seems to be some GitHub quirk. It won't affect us/you anyway. The API we use returns the correct commit. So no need to worry.

**Comment by omupenguin** [comment]
Okay!
