### ISSUE TITLE
Are we allowed to modify the format of commands?

### ISSUE THREAD

**Issue by otonashixav** [nusCS2113-AY1920S1/forum#22]
e.g. `event name @d/M/yyyy HHmm` instead of `event name /at d/M/yyyy HHmm`

I'm also guessing that we may attempt to accept as many date/time formats as possible and include the option to display it in different formats later in the project.

**Comment by otonashixav** [comment]
To clarify, I'm asking in the context of subsequent levels, rather than the level that requested the implementation, and ultimately our project.

**Comment by okkhoy** [comment]
Yes. You are allowed to do that in your project. 
When using symbols do take note of usability issues. If you can justify and convince that usability is not an issue, then it is fine.

**Comment by otonashixav** [comment]
Thanks
