### ISSUE TITLE
Questions regarding week 4 check

### ISSUE THREAD

**Issue by BrianTKM** [nusCS2113-AY1920S1/forum#37]
I would like to clarify a few things regarding week 4's check.

Here is my results of week 4's check:
<img width="512" alt="Capture" src="https://user-images.githubusercontent.com/54016584/64194995-f9164e80-ceb2-11e9-9c25-59169afd5b76.PNG">

And here is week 3's:
<img width="508" alt="Capture2" src="https://user-images.githubusercontent.com/54016584/64195266-a2f5db00-ceb3-11e9-8aba-5ba1a93e3d46.PNG">

A-Exceptions was not in week 3's check, so i didn't tag it in. Will I be penalised for not tagging this in even though it was not asked for in week 3's check?
Also isn't it suppose to be A-MoreOOP and not A-MoorOOP

Lastly, I have proper Level-6 and Level-9 tags, however the bot just returns the earlier tags it found. May I ask which tag will be graded

**Comment by okkhoy** [comment]
> A-Exceptions was not in week 3's check

It was under error handling, please check

>  isn't it suppose to be A-MoreOOP and not A-MoorOOP

Yes, it is a typo. We will fix the scoring in the backend.

>  I have proper Level-6 and Level-9 tags ...

The script checks for (e.g.,) Level-6 in the tag; so if you have got a tick for the activity, that means it has been considered completed.
