### ISSUE TITLE
nusCS2113-AY1920S1 github org Invitation not found

### ISSUE THREAD

**Issue by otonashixav** [nusCS2113-AY1920S1/forum#40]
Should I have received it already?
![image](https://user-images.githubusercontent.com/42372774/64400365-92ee1f00-d09e-11e9-90c7-4645ef578405.png)

**Comment by okkhoy** [comment]
Nope.. not yet! Maybe I should stop waiting for some of your classmates to provide their GitHub usernames so that I can send this invitation out.
