### ISSUE TITLE
JUnit tests: conceptual issues

### ISSUE THREAD

**Issue by aquohn** [nusCS2113-AY1920S1/forum#44]
Consider the hypothetical Command class that was referred to in Week 4

```
Command c = Parser.parse(fullCommand);
c.execute(tasks, ui, storage);
```

Assuming that these are the only two public interfaces of the Command class, how are we supposed to write unit tests for it?

- If we make the fields public we violate the public/private separation principle
- If we create dummy UI, storage and task list objects that defeats the whole purpose of unit testing
- If we implement copious numbers of trivial getters that are only used in test code, that is essentially dead code not used in the production build

What's the solution? Do we just bite the bullet and create the getters? Do we only unit test the larger components like UI, storage and task list objects?

**Comment by okkhoy** [comment]
Well, the `execute` methods does a few things and it is hard to separate out the dependencies to do unit tests. 
You can still check for the behavior when the values are null, some defaults, etc.
On the other hand, `parse` should be easy to unit-test.

Not sure if I understand your argument about using getters and setters.

**Comment by aquohn** [comment]
So the unit tests are mostly to catch obviously buggy behaviour?

From my own implementation of Command objects, the `parse` function will basically load them with the required parameters/arguments for them to execute. However, these parameters are private and are loaded via constructor, without public getters and setters (since Commands are pretty transient objects and would likely not need to be modified after creation).

In that case, should I create getters _just_ for my test code to get these private values, and to ensure they have been set properly? That would seem to be the most obvious way to ensure the parse function is setting up the Commands properly.

**Comment by okkhoy** [comment]
> So the unit tests are mostly to catch obviously buggy behaviour?

Unit tests are to test small parts of the code, in the process they should be able to catch any regressions.

It is more important to test the functionality of `parse` rather than to test if the return value is assigned properly to the variable. I think we can rely on Java for most parts to do the right thing there 🙂 

> That would seem to be the most obvious way to ensure the parse function is setting up the Commands properly

No! looks like you got somethings not 100% correct. To test the functionality of parse, you need to write unit test code for the `Parser` class not in the command class.

**Comment by aquohn** [comment]
To provide a concrete answer to this question, my friend suggested that I could do tests like checking the class of the returned Command to ensure that it is correct, even if I can't access its private fields to ensure that the parser was able to extract data for those fields.

In light of last week's tutorial and lecture, I have a slightly clearer picture now. Thanks!
