### ISSUE TITLE
Question about JUnit testing

### ISSUE THREAD

**Issue by rabhijit** [nusCS2113-AY1920S1/forum#49]
How comprehensive is our JUnit testing expected to be? Should we be testing every function in every class, or just a few general tests will do?

**Comment by aquohn** [comment]
From Slack:

![image](https://user-images.githubusercontent.com/42529939/64608277-dcbb6a00-d3fc-11e9-904d-649258cf79ff.png)

**Comment by rabhijit** [comment]
Beautiful, thanks!!
