### ISSUE TITLE
Are we allowed to use data taken from external open source APIs?

### ISSUE THREAD

**Issue by namiwa** [nusCS2113-AY1920S1/forum#53]
Would we be allowed to take data provided by external APIs which are not written in Java? For example https://api.nusmods.com/v2/ where they allow requests to attain module data in JSON format.

**Comment by okkhoy** [comment]
Yes. You can use external API (as long as it meets the criteria and is approved) and the data obtained from it. 
You cannot write parts of the project in other languages.

**Comment by namiwa** [comment]
@okkhoy Thanks for the clarification! With regards to the approval, which channels should we make our request?

**Comment by okkhoy** [comment]
Please use: #26 (which is pinned  on top of this issue tracker!)

**Comment by namiwa** [comment]
Noted, will close and make the request in #26.
