### ISSUE TITLE
Unclear on instructions for Team Tasks

### ISSUE THREAD

**Issue by saiganeshsuresh** [nusCS2113-AY1920S1/forum#54]
Firstly there is a statement saying we need to include the Duke Increments for the team task component apart from the A-Packages does this mean we need to have done J-Unit Testing and JavaDoc for the team repo? 
Secondly it is required to publish the documentation component of the team tasks as a developer guide? Is there any defined way to go about doing this?

**Comment by okkhoy** [comment]
I assume you are talking about this:
![image](https://user-images.githubusercontent.com/1023494/64701434-5de92e80-d4db-11e9-96cd-4ea8cb839ce4.png)

When you "port" the phase 1 code to your team repo, it should have all the things (read as all levels and all A-extensions) we did so far in Phase 1, including JUnit and JavaDoc.

Documentation aspects: Target profile, value proposition, user stories and use cases should be a part of the developer guide. You can write the developer guide using any software/tool (e.g., Google doc, MS Word, etc.) You don't have to publish the document, yet. We will ask you to submit a PDF version when it is time for review (typically week 6-7) look out for the information on the website/lecture/announcement. Towards the end of the project, you should make the document available in your repository.

**Comment by saiganeshsuresh** [comment]
Yes thank you, got it but do we have to tag all of them or just tag the v1.0 and A-Packages!

**Comment by okkhoy** [comment]
No need to tag all increments again in the team repo (No harm done if you have already tagged and pushed the tags!).
Just tag `v1.0` and `A-Packages`.
