### ISSUE TITLE
Image Nuke

### ISSUE THREAD

**Issue by maxxyx96** [nusCS2113-AY1920S1/forum#55]
Hi prof, your announcement for the cs2113 module nuked some of our LumiNUS dashboard. 

Would appreciate if you could help resolve the issue. 

Picture attached for your necessary reference.

Thank you!

![image](https://user-images.githubusercontent.com/36789831/64786249-a0c10a00-d5a0-11e9-8735-3c42ef0e3d3f.png)

**Comment by okkhoy** [comment]
Oh ouch! I didn't realize LumiNUS is this dumb.
I removed the image as the device has been found 🙂

**Comment by maxxyx96** [comment]
Thanks prof! :)
