### ISSUE TITLE
Exception in thread "main" java.util.NoSuchElementException: No line found

### ISSUE THREAD

**Issue by Jefferson111** [nusCS2113-AY1920S1/forum#7]
Encountered this while using Gradle run. Not sure if it's common knowledge, but apparently you need to add the following to your build.gradle:
```
run {
    standardInput = System.in
}
```

**Comment by D-uke** [comment]
RIP to those who tried to hasNextLine() 😂

**Comment by okkhoy** [comment]
@j-lum can you please clarify/comment on this?

**Comment by j-lum** [comment]
The buildfile was meant for students attempting the JavaFX tutorials and doesn't include the configurations needed for console applications. By default Gradle [defaults to an empty stdin](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:standardInput). 

We could set some sensible defaults for the students who opted to attempt `A-Gradle` early.

**Comment by okkhoy** [comment]
@j-lum 
> We could set some sensible defaults for the students who opted to attempt `A-Gradle` early.

Any suggestions on the default?

**Comment by j-lum** [comment]
Addressed this in : https://github.com/se-edu/duke/pull/13

**Comment by okkhoy** [comment]
Thanks @j-lum
