### ISSUE TITLE
Question on storage.

### ISSUE THREAD

**Issue by saiganeshsuresh** [nusCS2113-AY1920S1/forum#89]
For some implementations that store data but do not have to be human readable (meaning the user does not need to know this), is it okay to store them as such or do we need to make them human readable nonetheless!

**Comment by okkhoy** [comment]
Any data stored in the application has to be human-editable (from the project constraints)
![image](https://user-images.githubusercontent.com/1023494/68092397-94cd3680-fec5-11e9-892a-783af06282df.png)
If you are talking about configurations etc., it is necessary to make them human editable as well. (e.g., path of the data file can be specified by the user)

**Comment by saiganeshsuresh** [comment]
Yes I was asking in terms of configurations! Thank you!
